packages: []
catalogs:
  build:
    tsdown: ^0.21.8
  dev:
    bumpp: ^11.0.1
    pncat: ^0.11.1
    simple-git-hooks: ^2.13.1
    taze: ^19.11.0
    tsx: ^4.21.0
    typescript: ^6.0.2
  inlined:
    tildify: ^3.0.0
  lint:
    '@octohash/eslint-config': ^0.3.1
    eslint: ^10.2.0
    lint-staged: ^16.4.0
  prod:
    '@clack/prompts': ^1.2.0
    ansis: ^4.2.0
    cac: ^7.0.0
    code-finder: ^0.3.1
    detect-indent: ^7.0.2
    ofetch: ^1.5.1
    pathe: ^2.0.3
    unconfig: ^7.5.0
  test:
    vitest: ^4.1.4
  types:
    '@types/node': ^25.6.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - better-sqlite3
